server:
  port: 8095
spring:
  application:
    name: zuul-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka/   #注意要加eureka，不然找不到
zuul:
  routes:
    api-a:
      path: /api-a/**  #以/api-a/ 开头的请求都转发给ribbon-client服务
      serviceId: ribbon-client
    api-b:
      path: /api-b/**  #以/api-b/ 开头的请求都转发给feign-client服务
      serviceId: feign-client