server:
  port: 8096
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master  #配置仓库分支
      server:
        git:
          uri: https://github.com/xuanfong1/SpringCould/   #配置仓库git地址
          search-paths: config/testrepo   #配置仓库路径
#          username:   #访问git仓库的用户名，这里因为是开放项目所以不需要设置
#          password:   #访问git仓库的密码