server:
  port: 8096
spring:
  application:
    name: config-server
  profiles:
    active: native  #这里进行仓库预选，可设置native和git，分别对应spring.cloud.config.server下面的值
  cloud:
    config:
      label: master  #配置仓库分支
      server:
        git:
          uri: https://github.com/xuanfong1/SpringCould/   #配置仓库git地址
          search-paths: config/testrepo   #配置仓库路径
#          username:   #访问git仓库的用户名，这里因为是开放项目所以不需要设置
#          password:   #访问git仓库的密码
        native: #本地配置文件仓库的绝对路径
          search-locations: /Users/xuanleung/workspace/SpringCould/config/testrepo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka/ #注意要加eureka，不然找不到